### ISSUE TITLE
 "byteswap.h"

### ISSUE THREAD

**Issue by zhengKey** [VictorGerin/QT-UDP_Hole_Punching#4]
where is "byteswap.h" .I cannot build success.

**Comment by VictorGerin** [comment]
It's true, i have build using a linux pc however i'm only using "byteswap.h" for __bswap_XX (__bswap_16, __bswap_32 and __bswap_64), that the goal is change from big endian to little endian.

You can use "#include QtEndian" and them "T qToLittleEndian(src T)" probably. Actually is better use qToLittleEndian because this method takes in account the endiness of the current PC. 

Just take care to not change the size (in bytes) of some variable

If u success please make a pull request i will approve, and any thing else please tell me.

**Comment by zhengKey** [comment]
hello, Is it able to travel the symmetric nat, why I always run the result "Deu merda STUN";




------------------ 原始邮件 ------------------
发件人: "Victor Gerin de Lacerda"<notifications@github.com>;
发送时间: 2019年8月19日(星期一) 晚上9:47
收件人: "VictorGerin/QT-UDP_Hole_Punching"<QT-UDP_Hole_Punching@noreply.github.com>;
抄送: "郑炜铭"<745862995@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [VictorGerin/QT-UDP_Hole_Punching]  "byteswap.h" (#4)




It's true, i have build using a linux pc however i'm only using "byteswap.h" for __bswap_XX (__bswap_16, __bswap_32 and __bswap_64), that the goal is change from big endian to little endian.
 
U can use "#include " and them "T qToLittleEndian(src T)" probably. Actually is better use qToLittleEndian because this method that in account the endiness of the current PC.
 
If u success please make a pull request i will approve, and any thing else please tell me.

**Comment by VictorGerin** [comment]
Ow.. That may be a good news :)

When a have create this code is to make UDP hole punching without any custom server and i have done that using public STUN server and public torrent Tracker server in combination.

The first and import step is establish some connection with the STUN server and because that i have to has a full control of all menages i have to implement some crude simple STUN protocol code.

One first step, that now a see is wrong is in my code is Create a random Transaction_ID (this u can see in the stunclient.cpp file at line 88) This Transaction_ID must be unique during some communication cycle (send and receive) of the STUN protocol.

If the server responds a wrong Transaction_ID that message must be ignored, but my code is very simple and don't know how to  handle that, that is the cause you receive this odd message (sorry about that).

The possible problems is;
1º Your Stun server is really send all times the wrong Transaction_ID. I Don't believe is that is the case.
2º Is possible that you may sending some Transaction_ID but because of the BIg_enndian trouble your machine is interpret wrong the receive Transaction_ID.

The best way to know whats really happens is using some kind sniffer i highly recommend use the Wireshark for that set filter for UDP protoclo and the IP of your current STUN server.

Obs: in my code i have HardCoded the IP and port of the STUN srever in the file Conn.cpp here 
(https://github.com/VictorGerin/QT-UDP_Hole_Punching/blob/4ab1f59c6a5014b79de702dd2840e1cb2c8ea29b/conn.cpp#L6)

When u do this test please send to me the sniffers packages readed i will be able to more about this problem

Obs2: I have mentioned that has a erre in my code in this line 
https://github.com/VictorGerin/QT-UDP_Hole_Punching/blob/4ab1f59c6a5014b79de702dd2840e1cb2c8ea29b/stunclient.cpp#L57
The verification must be with the OR logic not with the AND logic that because if any part of the Transaction_ID is wrong you must drop out the message.
